# syntax = btidor-syntax-dev

FROM ubuntu AS a
COPY nodesource.sources /etc/apt/sources.list.d/
ADD --apt nodejs

FROM debian AS b
COPY nodesource.sources /etc/apt/sources.list.d/
ADD --apt nodejs

FROM scratch
COPY --from=a / /ubuntu
COPY --from=b / /debian
